---
- hosts: virtualbox
  remote_user: axt
  become: true
  roles:
    - freeswitch
  vars:
    repository: https://github.com/signalwire/freeswitch.git
    version: v1.10
    socket:
      nat-map: "true"
      listen-port: 8021
      password: ClueCon
      listen-ip: "0.0.0.0"
      stop-on-bind-error: "true"
      apply-inbound-acl: "localnet.auto"